config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :students
  resources :courses
  resources :classrooms
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student, inverse_of: :classrooms
  belongs_to :course, inverse_of: :classrooms

  before_create :set_entry_at

  private
  def set_entry_at
    self.entry_at = Time.now
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms, inverse_of: :course
  has_many :students, through: :classrooms
  enum status: [:active, :inactive]
  validates_presence_of :name, :description, :status
  validates_uniqueness_of :name
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms, inverse_of: :course
  has_many :courses, through: :classrooms
  enum status: [:active, :inactive]
  validates_presence_of :name, :register_number, :status
  validates_uniqueness_of :register_number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  def index
    @classrooms = Classroom.all
  end

  def show
    @classroom = Classroom.find(params[:id])
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      flash[:success] = 'Matrícula criada com sucesso!'
      redirect_to classrooms_path
    else
      render action: :new
    end
  end

  def destroy
    @classroom = Classroom.find(params[:id])

    if @classroom.destroy
      flash[:sucess] = 'Matrícula apagada!'
      redirect_to classrooms_path
    else
      render action: :index
    end
  end

  private
  def classroom_params
    params.require(:classroom).permit(:student_id, :course_id)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:success] = 'Curso criado com sucesso!'
      redirect_to courses_path
    else
      render action: :new
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update_attributes(course_params)
      flash[:sucess] = 'Curso atualizado com sucesso!'
      redirect_to courses_path
    else
      render action: :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])

    if @course.destroy
      flash[:sucess] = 'Curso apagado!'
      redirect_to courses_path
    else
      render action: :index
    end
  end

  private
  def course_params
    params.require(:course).permit(:name, :description, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      flash[:success] = 'Aluno criado com sucesso!'
      redirect_to students_path
    else
      render action: :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update_attributes(student_params)
      flash[:sucess] = 'Aluno atualizado com sucesso!'
      redirect_to students_path
    else
      render action: :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])

    if @student.destroy
      flash[:sucess] = 'Aluno apagado!'
      redirect_to students_path
    else
      render action: :index
    end
  end

  private
  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice, :success
        "success"
      when :alert, :error
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_classroom.html.erb
<p><%= link_to classroom.id, classroom_path(classroom) %> </p>

<%= link_to 'deletar', classroom_path(classroom), method: :delete, data: { confirm: "Tem certeza que deseja apagar essa #{ tm(Classroom) }?" }, class: 'delete' %>

app/views/classrooms/_form.html.erb
<%= simple_form_for @classroom do |f| %>
  <%= f.association :student %>
  <%= f.association :course %>
  <%= f.button :submit %>
<% end %>

app/views/classrooms/index.html.erb
<h3><%= tmp(Classroom) %></h3>

<% if @classrooms.empty? %>
  <p><%= "Não existem #{ tmp(Classroom) } cadastradas." %></p>
<% else %>
  <%= render @classrooms %>
<% end %>

<br />

<%= link_to "Nova #{ tm(Classroom) }", new_classroom_path %>

app/views/classrooms/new.html.erb
<%= "Nova #{ tm(Classroom) }" %>

<%= render partial: 'form' %>

app/views/classrooms/show.html.erb
<p><%= "#{ tm(Student) }: "%> <%= link_to @classroom.student.name, student_path(@classroom.student) %></p>
<p><%= "#{ tm(Course) }: " %> <%= link_to @classroom.course.name, course_path(@classroom.course) %></p>
<p><%= "#{ ta(Classroom, :entry_at) }: "%> <%= l(@classroom.entry_at) %></p>

app/views/courses/_course.html.erb
<p><%= link_to course.name, course_path(course) %> </p>

<%= link_to 'editar', edit_course_path(course) %>
<%= link_to 'deletar', course_path(course), method: :delete, data: { confirm: "Tem certeza que deseja apagar esse #{ tm(Course) }?" }, class: 'delete' %>

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :status, collection: [:active, :inactive] %>
  <%= f.button :submit %>
<% end %>

app/views/courses/edit.html.erb
<%= "Editar #{ tm(Course) }" %>

<%= render partial: 'form' %>

app/views/courses/index.html.erb
<h3><%= tmp(Course) %></h3>

<% if @courses.empty? %>
  <p><%= "Não existem #{ tmp(Course) } cadastrados." %></p>
<% else %>
  <%= render @courses %>
<% end %>

<br />

<%= link_to "Novo #{ tm(Course) }", new_course_path %>

app/views/courses/new.html.erb
<%= "Novo #{ tm(Course) }" %>

<%= render partial: 'form' %>

app/views/courses/show.html.erb
<p><%= "#{ ta(Course, :name) }: #{ @course.name }" %></p>
<p><%= "#{ ta(Course, :description) }: #{ @course.description }" %></p>
<p><%= "#{ ta(Course, :status) }: #{ @course.status }" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash_messages %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h3>Proficiency Test</h3>

<%= link_to tm(Course, 2), courses_path %>
<%= link_to tm(Student, 2), students_path %>
<%= link_to tm(Classroom, 2), classrooms_path %>

app/views/students/_form.html.erb
<%= simple_form_for @student do |f| %>
  <%= f.input :name %>
  <%= f.input :register_number %>
  <%= f.input :status, collection: [:active, :inactive] %>
  <%= f.button :submit %>
<% end %>

app/views/students/_student.html.erb
<p><%= link_to student.name, student_path(student) %> </p>

<%= link_to 'editar', edit_student_path(student) %>
<%= link_to 'deletar', student_path(student), method: :delete, data: { confirm: "Tem certeza que deseja apagar esse #{ tm(Student) }?" }, class: 'delete' %>

app/views/students/edit.html.erb
<%= "Editar #{ tm(Student) }" %>

<%= render partial: 'form' %>

app/views/students/index.html.erb
<h3><%= tmp(Student) %></h3>

<% if @students.empty? %>
  <p><%= "Não existem #{ tmp(Student) } cadastrados." %></p>
<% else %>
  <%= render @students %>
<% end %>

<br />

<%= link_to "Novo #{ tm(Student) }", new_student_path %>

app/views/students/new.html.erb
<%= "Novo #{ tm(Student) }" %>

<%= render partial: 'form' %>

app/views/students/show.html.erb
<p><%= "#{ ta(Student, :name) }: #{ @student.name }" %></p>
<p><%= "#{ ta(Student, :register_number) }: #{ @student.register_number }" %></p>
<p><%= "#{ ta(Student, :status) }: #{ @student.status }" %></p>